version: 0.4.7

namespace: ma3ady
project: ma3ady

services:
  - name: marketing
    context: marketing
    image: ghcr.io/markmorcos/ma3ady-marketing
    port: 8080

    env:
      - name: APEX_HOST
        value: ma3ady.com
      - name: NODE_ENV
        value: production

    ingress:
      host: ma3ady.com
      path: /
      pathType: Prefix
