import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Ban,
  Bell,
  Calendar,
  CalendarClock,
  CalendarPlus,
  Car,
  Check,
  CheckCheck,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  Clock,
  Copy,
  CreditCard,
  Edit3,
  Eye,
  Globe,
  Hand,
  Heart,
  History,
  Home,
  Info,
  Link as LinkIcon,
  ListChecks,
  Mail,
  MapPin,
  Moon,
  MoreVertical,
  Pencil,
  Phone,
  Plus,
  QrCode,
  Repeat,
  Scissors,
  Search,
  Send,
  Settings,
  Share2,
  Sliders,
  Sparkles,
  Stethoscope,
  Sun,
  Sunrise,
  Trash2,
  TriangleAlert,
  User,
  UserPlus,
  Users,
  X,
  XCircle,
  type LucideIcon,
} from 'lucide-react-native';
import { useTheme } from '@/design/ThemeProvider';
import { type ColorToken, resolveColor } from '@/design/theme';

const ICONS = {
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  ban: Ban,
  bell: Bell,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  'calendar-plus': CalendarPlus,
  car: Car,
  check: Check,
  'check-check': CheckCheck,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  clock: Clock,
  copy: Copy,
  'credit-card': CreditCard,
  edit: Edit3,
  eye: Eye,
  globe: Globe,
  hand: Hand,
  heart: Heart,
  history: History,
  home: Home,
  info: Info,
  link: LinkIcon,
  'list-checks': ListChecks,
  mail: Mail,
  'map-pin': MapPin,
  moon: Moon,
  'more-vertical': MoreVertical,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  'qr-code': QrCode,
  repeat: Repeat,
  scissors: Scissors,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  sliders: Sliders,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  sun: Sun,
  sunrise: Sunrise,
  trash: Trash2,
  'triangle-alert': TriangleAlert,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  x: X,
  'x-circle': XCircle,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

type Props = {
  name: IconName;
  size?: number;
  color?: ColorToken;
  /** Escape hatch for callers (like react-navigation tab bars) that hand us a
   *  raw color string instead of a design-system token. Wins over `color`. */
  colorHex?: string;
};

export function Icon({ name, size = 20, color = 'text', colorHex }: Props) {
  const theme = useTheme();
  const LucideComp = ICONS[name];
  const resolved = colorHex ?? resolveColor(theme, color);
  return <LucideComp size={size} color={resolved} />;
}
